# Make the Python module called user_particle_boundary_functions_solib

THE_MODULE_NAME = user_particle_boundary_functions_solib

DFLAGS = -DMODULE_NAME=$(THE_MODULE_NAME)

$(THE_MODULE_NAME).cpython-36m-x86_64-linux-gnu.so: $(THE_MODULE_NAME).cpp UserParticleBoundaryFunctions.h
	c++ $(DFLAGS) -O3 -Wall -shared -std=c++11 -fPIC -fvisibility=hidden `python3 -m pybind11 --includes` $(THE_MODULE_NAME).cpp -o $@

clean:
	/bin/rm $(THE_MODULE_NAME).cpython-36m-x86_64-linux-gnu.so
