# Make the Python module called numpy_types_solib

numpy_types_solib.cpython-36m-x86_64-linux-gnu.so: numpy_types_solib.cpp Pstruct.h
	c++ -O3 -Wall -shared -std=c++11 -fPIC -fvisibility=hidden -I/usr/include/eigen3 `python3 -m pybind11 --includes` numpy_types_solib.cpp -o numpy_types_solib`python3-config --extension-suffix`

clean:
	/bin/rm numpy_types_solib.cpython-36m-x86_64-linux-gnu.so
